### ISSUE TITLE
android gradle:4.2.1

### ISSUE THREAD

**Issue by bhk545145** [flutterbest/flutter_alibc_kit#2]
D/NetworkSecurityConfig(19458): No Network Security Config specified, using platform default
I/DpmTcmClient(19458): RegisterTcmMonitor from: $Proxy0
I/eyun.goodthing(19458): Waiting for a blocking GC ClassLinker
E/AndroidRuntime(19458): FATAL EXCEPTION: SDK Looper Thread
E/AndroidRuntime(19458): Process: com.taokeyun.goodthings, PID: 19458
E/AndroidRuntime(19458): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/alibaba/fastjson/JSONObject;
E/AndroidRuntime(19458): 	at com.alibaba.baichuan.trade.biz.core.config.AlibcConfigService.init(Unknown Source:39)
E/AndroidRuntime(19458): 	at com.alibaba.baichuan.trade.biz.AlibcMiniTradeBiz.init(Unknown Source:24)
E/AndroidRuntime(19458): 	at com.alibaba.baichuan.trade.biz.AlibcTradeBiz.init(Unknown Source:30)
E/AndroidRuntime(19458): 	at com.alibaba.baichuan.android.trade.AlibcTradeSDK.b(Unknown Source:3)
E/AndroidRuntime(19458): 	at com.alibaba.baichuan.android.trade.AlibcTradeSDK.a(Unknown Source:0)
E/AndroidRuntime(19458): 	at com.alibaba.baichuan.android.trade.AlibcTradeSDK$1.run(Unknown Source:4)
E/AndroidRuntime(19458): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(19458): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(19458): 	at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(19458): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/AndroidRuntime(19458): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.alibaba.fastjson.JSONObject" on path: DexPathList[[zip file "/data/app/com.taokeyun.goodthings-YI0S9FiOLE3RjQErhVTbnw==/base.apk"],nativeLibraryDirectories=[/data/app/com.taokeyun.goodthings-YI0S9FiOLE3RjQErhVTbnw==/lib/arm64, /data/app/com.taokeyun.goodthings-YI0S9FiOLE3RjQErhVTbnw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
E/AndroidRuntime(19458): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:230)
E/AndroidRuntime(19458): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(19458): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(19458): 	... 10 more

**Comment by bhk545145** [comment]
跑起来就直接崩溃了

**Comment by flutterbest** [comment]
classpath 'com.android.tools.build:gradle:3.4.3'

**Comment by flutterbest** [comment]
<img width="869" alt="image" src="https://user-images.githubusercontent.com/4466086/164890281-b2887dd9-83aa-48b2-bfed-8f3ef2d32870.png">

**Comment by flutterbest** [comment]
https://github.com/flutterbest/flutter_alibc_kit/issues/3
