### ISSUE TITLE
大佬，这个问题怎么解决？

### ISSUE THREAD

**Issue by xfu008** [flutterbest/flutter_alibc_kit#4]
![QQ截图20220426180132](https://user-images.githubusercontent.com/48432551/165275838-1619ce70-f5f7-484e-a30b-6a456424d47b.png)

**Comment by flutterbest** [comment]
1. flutter clean
2. 删除Podfile.lock
3. 重新pod install

**Comment by xfu008** [comment]
不行，include of non-modular header inside framework module 'flutter_alibc.FlutterAlibcPlugin': '/Users/demo/ios/.symlinks/plugins/flutter_alibc/ios/Source/framework/AliAuthSDK/AlibabaAuthEntrance.framework/Headers/ALBBSDK.h'

**Comment by flutterbest** [comment]
你把ios目录改为oc的试试  https://stackoverflow.com/questions/68365355/inlude-of-non-modular-header-inside-framework-module

**Comment by xfu008** [comment]
#use_frameworks! 注释后解决了我的问题

**Comment by danieldai** [comment]
#use_frameworks! 能够暂时解决这个问题，但是要根治这个问题需要用objc重写这个插件
